// Curated static book data.
// gutenbergId is used to fetch full text and cover image from Project Gutenberg.

export const CATEGORIES = ['All', 'Classic', 'Adventure', 'Romance', 'Mystery', 'Philosophy', 'Science', 'Poetry']

const gutenbergCover = (gutenbergId) => `https://www.gutenberg.org/cache/epub/${gutenbergId}/pg${gutenbergId}.cover.medium.jpg`

export const BOOKS = [
  {
    id: 1,
    gutenbergId: 1342,
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    year: 1813,
    category: 'Romance',
    cover: gutenbergCover(1342),
    description: 'A witty exploration of love, class, and marriage in Regency-era England through the spirited Elizabeth Bennet.',
    pages: 432,
    rating: 4.9,
  },
  {
    id: 2,
    gutenbergId: 64317,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    year: 1925,
    category: 'Classic',
    cover: gutenbergCover(64317),
    description: "A portrait of the Jazz Age — obsession, wealth, and the elusive American Dream seen through Nick Carraway's eyes.",
    pages: 180,
    rating: 4.7,
  },
  {
    id: 3,
    gutenbergId: 2701,
    title: 'Moby Dick',
    author: 'Herman Melville',
    year: 1851,
    category: 'Adventure',
    cover: gutenbergCover(2701),
    description: "Captain Ahab's obsessive quest to hunt the legendary white whale across the vast, unforgiving seas.",
    pages: 635,
    rating: 4.5,
  },
  {
    id: 4,
    gutenbergId: 244,
    title: 'Sherlock Holmes: A Study in Scarlet',
    author: 'Arthur Conan Doyle',
    year: 1887,
    category: 'Mystery',
    cover: gutenbergCover(244),
    description: "The first meeting of Holmes and Watson as they untangle a mysterious murder in London's foggy streets.",
    pages: 192,
    rating: 4.8,
  },
  {
    id: 5,
    gutenbergId: 11,
    title: "Alice's Adventures in Wonderland",
    author: 'Lewis Carroll',
    year: 1865,
    category: 'Classic',
    cover: gutenbergCover(11),
    description: 'Alice tumbles down a rabbit hole into a whimsical world filled with peculiar creatures and impossible logic.',
    pages: 163,
    rating: 4.7,
  },
  {
    id: 6,
    gutenbergId: 1260,
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    year: 1847,
    category: 'Romance',
    cover: gutenbergCover(1260),
    description: "An orphan's passionate journey from hardship to love, challenging Victorian society's rigid class boundaries.",
    pages: 507,
    rating: 4.8,
  },
  {
    id: 7,
    gutenbergId: 74,
    title: 'The Adventures of Tom Sawyer',
    author: 'Mark Twain',
    year: 1876,
    category: 'Adventure',
    cover: gutenbergCover(74),
    description: "The mischievous escapades of Tom Sawyer along the Mississippi River — a timeless American coming-of-age story.",
    pages: 274,
    rating: 4.6,
  },
  {
    id: 8,
    gutenbergId: 84,
    title: 'Frankenstein',
    author: 'Mary Shelley',
    year: 1818,
    category: 'Classic',
    cover: gutenbergCover(84),
    description: "Victor Frankenstein's tragic experiment in creation raises timeless questions about science, ethics, and humanity.",
    pages: 280,
    rating: 4.6,
  },
  {
    id: 9,
    gutenbergId: 1727,
    title: 'The Odyssey',
    author: 'Homer',
    year: -800,
    category: 'Classic',
    cover: gutenbergCover(1727),
    description: "Odysseus's epic ten-year voyage home from Troy, battling gods, monsters, and the temptations of mortals.",
    pages: 374,
    rating: 4.7,
  },
  {
    id: 10,
    gutenbergId: 2554,
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    year: 1866,
    category: 'Mystery',
    cover: gutenbergCover(2554),
    description: "A student's murder triggers a profound psychological descent into guilt, redemption, and the human conscience.",
    pages: 549,
    rating: 4.8,
  },
  {
    id: 11,
    gutenbergId: 996,
    title: 'Don Quixote',
    author: 'Miguel de Cervantes',
    year: 1605,
    category: 'Classic',
    cover: gutenbergCover(996),
    description: 'A deluded knight and his loyal squire embark on absurd chivalric adventures in a satirical Spanish masterpiece.',
    pages: 982,
    rating: 4.6,
  },
  {
    id: 12,
    gutenbergId: 2680,
    title: 'Meditations',
    author: 'Marcus Aurelius',
    year: 180,
    category: 'Philosophy',
    cover: gutenbergCover(2680),
    description: "The Roman Emperor's private Stoic reflections on virtue, mortality, and the art of living a purposeful life.",
    pages: 254,
    rating: 4.9,
  },
  {
    id: 13,
    gutenbergId: 1497,
    title: 'The Republic',
    author: 'Plato',
    year: -380,
    category: 'Philosophy',
    cover: gutenbergCover(1497),
    description: 'Socrates explores justice, the ideal state, and the philosopher-king in this foundational work of Western thought.',
    pages: 416,
    rating: 4.7,
  },
  {
    id: 14,
    gutenbergId: 36,
    title: 'The War of the Worlds',
    author: 'H.G. Wells',
    year: 1898,
    category: 'Science',
    cover: gutenbergCover(36),
    description: 'Martian invaders lay siege to Victorian England in this groundbreaking science fiction tale of alien invasion.',
    pages: 212,
    rating: 4.5,
  },
  {
    id: 15,
    gutenbergId: 35,
    title: 'The Time Machine',
    author: 'H.G. Wells',
    year: 1895,
    category: 'Science',
    cover: gutenbergCover(35),
    description: 'A Victorian inventor travels 800,000 years into the future to discover a fractured, post-human civilization.',
    pages: 118,
    rating: 4.5,
  },
  {
    id: 16,
    gutenbergId: 1322,
    title: 'Leaves of Grass',
    author: 'Walt Whitman',
    year: 1855,
    category: 'Poetry',
    cover: gutenbergCover(1322),
    description: "Whitman's revolutionary free-verse celebration of democracy, nature, the body, and the American spirit.",
    pages: 145,
    rating: 4.6,
  },
  {
    id: 17,
    gutenbergId: 345,
    title: 'Dracula',
    author: 'Bram Stoker',
    year: 1897,
    category: 'Mystery',
    cover: gutenbergCover(345),
    description: "Jonathan Harker's chilling encounter with Count Dracula in Transylvania unleashes a centuries-old evil.",
    pages: 418,
    rating: 4.7,
  },
  {
    id: 18,
    gutenbergId: 768,
    title: 'Wuthering Heights',
    author: 'Emily Brontë',
    year: 1847,
    category: 'Romance',
    cover: gutenbergCover(768),
    description: 'The dark, passionate love between Heathcliff and Catherine tears across generations on the wild Yorkshire moors.',
    pages: 342,
    rating: 4.7,
  },
  {
    id: 19,
    gutenbergId: 174,
    title: 'The Picture of Dorian Gray',
    author: 'Oscar Wilde',
    year: 1890,
    category: 'Classic',
    cover: gutenbergCover(174),
    description: "A beautiful young man sells his soul for eternal youth as his portrait bears the mark of his moral corruption.",
    pages: 254,
    rating: 4.8,
  },
  {
    id: 20,
    gutenbergId: 103,
    title: 'Around the World in Eighty Days',
    author: 'Jules Verne',
    year: 1872,
    category: 'Adventure',
    cover: gutenbergCover(103),
    description: 'Phileas Fogg bets his fortune he can circumnavigate the globe in just 80 days — the ultimate Victorian race.',
    pages: 252,
    rating: 4.6,
  },
  {
    id: 21,
    gutenbergId: 164,
    title: 'Twenty Thousand Leagues Under the Sea',
    author: 'Jules Verne',
    year: 1870,
    category: 'Adventure',
    cover: gutenbergCover(164),
    description: "Captain Nemo pilots the Nautilus through the ocean depths in this visionary underwater odyssey.",
    pages: 398,
    rating: 4.6,
  },
  {
    id: 22,
    gutenbergId: 6130,
    title: 'The Iliad',
    author: 'Homer',
    year: -750,
    category: 'Classic',
    cover: gutenbergCover(6130),
    description: 'The rage of Achilles fuels the defining battles of the Trojan War in this epic poem of heroes and gods.',
    pages: 683,
    rating: 4.7,
  },
  {
    id: 23,
    gutenbergId: 28054,
    title: 'The Brothers Karamazov',
    author: 'Fyodor Dostoevsky',
    year: 1880,
    category: 'Philosophy',
    cover: gutenbergCover(28054),
    description: "Three brothers' spiritual and moral battle over faith, free will, and a father's murder — Dostoevsky's magnum opus.",
    pages: 796,
    rating: 4.9,
  },
  {
    id: 24,
    gutenbergId: 161,
    title: 'Sense and Sensibility',
    author: 'Jane Austen',
    year: 1811,
    category: 'Romance',
    cover: gutenbergCover(161),
    description: 'Two sisters navigate love and heartbreak: one ruled by reason, the other by emotion, in Georgian England.',
    pages: 374,
    rating: 4.7,
  },
]
